services:
  gateway:
    build: ./services/gateway
    volumes:
      - ./services/gateway:/service
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - queries-processor
  queries-processor:
    build: ./services/queries-processor
    volumes:
      - ./services/queries-processor:/service
    ports:
      - "3001:3000"
    depends_on:
      - redis
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./db/mongo/data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  redis:
    image: redis
    restart: always
    volumes:
      - ./db/redis/data:/data
    ports:
      - "6379:6379"